repos:
  - repo: local
    hooks:
      - id: version-check
        name: Ensure version strings are updated
        entry: python scripts/version_check.py
        language: python
        types: [python, markdown]
